/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Componentes.UtilidadFuentes;
import java.awt.Color;
import javax.swing.JOptionPane;
import capa_datos.MaterialDAO;
import capa_logica.Material;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author JIMMYSIN
 */
public class jdFuncionesMaterial extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdFuncionesMaterial.class.getName());

    // Definimos los modos posibles
    public enum Modo {
        AGREGAR, EDITAR, ELIMINAR
    }
    private Modo modoActual;
    private String idMaterialSeleccionado; // Para saber qué registro editar/eliminar

    /**
     * Creates new form jdFuncionesMaterial
     */
    public jdFuncionesMaterial(java.awt.Frame parent, boolean modal, Modo modo, String idMaterial) {
        super(parent, modal);
        initComponents();

        setResizable(false);
        // Spinner: valor inicial 0, mínimo 0, sin máximo, incrementos de 1
        spnStock.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));

        lblTitle.setFont(UtilidadFuentes.cargarFuenteVarsity(28f));
        aplicarEstiloBordesTecnicos();

        this.modoActual = modo;
        this.idMaterialSeleccionado = idMaterial;

        this.setLocationRelativeTo(null);

        configurarModoVisual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelContenedor = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        spnStock = new javax.swing.JSpinner();
        txtDescripcion = new javax.swing.JTextField();
        chkVigencia = new javax.swing.JCheckBox();
        txtCategoria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));

        lblNombre.setText("Nombre");

        lblCodigo.setText("Código");

        lblDescripcion.setText("Descripción");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        lblVigencia.setText("Vigencia");

        lblCategoria.setText("Categoría");

        txtCodigo.addActionListener(this::txtCodigotxtCodigoActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        chkVigencia.setText("(Vigente)");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDescripcion)
                        .addComponent(lblCodigo)
                        .addComponent(lblNombre)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(txtNombre)
                        .addComponent(txtCodigo))
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                            .addComponent(lblStock)
                            .addGap(93, 93, 93))
                        .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelContenedorLayout.createSequentialGroup()
                            .addComponent(lblVigencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCategoria))
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNombre)
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkVigencia)
                            .addComponent(lblVigencia))))
                .addGap(23, 23, 23)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jPanelFondo.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 330));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(232, 108, 54));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnGuardar.setText("| Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHideActionText(true);
        btnGuardar.setIconTextGap(15);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanelFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 180, -1));

        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setText("Gestión de Materiales");
        jPanelFondo.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 400, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoTecnico.png"))); // NOI18N
        jPanelFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 510, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigotxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigotxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigotxtCodigoActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setBackground(new Color(255, 200, 150));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Dependiendo del modo actual, ejecutamos la acción correspondiente
        switch (modoActual) {
            case AGREGAR:
                if (!validarCampos()) {
                    return;
                }
                try {
                    if (txtCodigo.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Ingrese el código del material.");
                        txtCodigo.requestFocus();
                        return;
                    }
                    if (txtNombre.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Ingrese el nombre del material.");
                        txtNombre.requestFocus();
                        return;
                    }
                    if (txtPrecio.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                "Ingrese el precio.");
                        txtPrecio.requestFocus();
                        return;
                    }
                    float precio = Float.parseFloat(txtPrecio.getText());

                    if (precio <= 0) {
                        JOptionPane.showMessageDialog(this,
                                "El precio debe ser mayor que cero.");
                        txtPrecio.requestFocus();
                        return;
                    }

                    int stock = (int) spnStock.getValue();

                    if (stock < 0) {
                        JOptionPane.showMessageDialog(this,
                                "El stock no puede ser negativo.");
                        spnStock.requestFocus();
                        return;
                    }

                    String codigo = txtCodigo.getText().trim();
                    if (MaterialDAO.consultarPorCodigo(codigo) != null) {
                        JOptionPane.showMessageDialog(this, "Ya existe un material con ese código.");
                        return;
                    }
                    Material nuevo = new Material(
                            codigo, txtNombre.getText().trim(), txtDescripcion.getText().trim(),
                            Float.parseFloat(txtPrecio.getText().trim()), (int) spnStock.getValue(),
                            txtCategoria.getText().trim(), chkVigencia.isSelected()
                    );
                    MaterialDAO.agregar(nuevo);
                    JOptionPane.showMessageDialog(this, "Material registrado exitosamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al registrar: " + ex.getMessage());
                    return;
                }
                break;

            case EDITAR:
                if (!validarCampos()) {
                    return;
                }
                try {
                    Material actualizado = new Material(
                            idMaterialSeleccionado, txtNombre.getText().trim(), txtDescripcion.getText().trim(),
                            Float.parseFloat(txtPrecio.getText().trim()), (int) spnStock.getValue(),
                            txtCategoria.getText().trim(), chkVigencia.isSelected()
                    );
                    MaterialDAO.modificar(actualizado);
                    JOptionPane.showMessageDialog(this, "Material actualizado exitosamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage());
                    return;
                }
                break;

            case ELIMINAR:
                try {
                    int confirmar = JOptionPane.showConfirmDialog(this,
                            "¿Está seguro de eliminar el material \"" + txtNombre.getText() + "\"?",
                            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
                    if (confirmar != JOptionPane.YES_OPTION) {
                        return;
                    }

                    MaterialDAO.borrar(idMaterialSeleccionado);
                    JOptionPane.showMessageDialog(this, "Material eliminado exitosamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
                    return;
                }
                break;
        }
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarModoVisual() {
        switch (modoActual) {
            case AGREGAR:
                setTitle("Registrar Nuevo Material");

                btnGuardar.setText("GUARDAR");
                limpiarCampos();
                txtCodigo.setEditable(true);
                break;

            case EDITAR:
                setTitle("Editar Material");
                btnGuardar.setText("ACTUALIZAR");
                cargarDatosMaterial(idMaterialSeleccionado);
                txtCodigo.setEnabled(false); // El codigo no debe cambiar en edicion
                break;

            case ELIMINAR:
                setTitle("Eliminar Material");
                btnGuardar.setText("ELIMINAR");
                cargarDatosMaterial(idMaterialSeleccionado);
                bloquearCampos(false);
                break;
        }
    }

    private void bloquearCampos(boolean activar) {
        txtCodigo.setEnabled(activar);
        txtNombre.setEnabled(activar);
        txtDescripcion.setEnabled(activar);
        txtPrecio.setEnabled(activar);
        spnStock.setEnabled(activar);
        chkVigencia.setEnabled(activar);
        txtCategoria.setEnabled(activar);

    }

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        spnStock.setValue(0);
        chkVigencia.setSelected(false);
        txtCategoria.setText("");

    }

    private void cargarDatosMaterial(String codigo) {
        try {
            Material m = MaterialDAO.consultarPorCodigo(codigo);
            if (m != null) {
                txtCodigo.setText(m.getCodigo());
                txtNombre.setText(m.getNombre());
                txtDescripcion.setText(m.getDescripcion());
                txtPrecio.setText(String.valueOf(m.getPrecio()));
                spnStock.setValue(m.getStock());
                chkVigencia.setSelected(m.isVigencia());
                txtCategoria.setText(m.getCategoria());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el material: " + ex.getMessage());
        }
    }

    private boolean validarCampos() {
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código es obligatorio.");
            return false;
        }
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return false;
        }
        try {
            float precio = Float.parseFloat(txtPrecio.getText().trim());
            if (precio < 0) {
                JOptionPane.showMessageDialog(this, "El precio no puede ser negativo.");
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.");
            return false;
        }

        int stock = (int) spnStock.getValue();
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "El stock no puede ser negativo.");
            return false;
        }
        return true;
    }

    private void aplicarEstiloBordesTecnicos() {
        String estiloCampos = "arc: 4; borderWidth: 1; borderColor: #000099; focusColor: #EB5A0A;";

        txtCodigo.putClientProperty("FlatLaf.style", estiloCampos);
        txtNombre.putClientProperty("FlatLaf.style", estiloCampos);
        txtDescripcion.putClientProperty("FlatLaf.style", estiloCampos);
        txtPrecio.putClientProperty("FlatLaf.style", estiloCampos);
        spnStock.putClientProperty("FlatLaf.style", estiloCampos);
        txtCategoria.putClientProperty("FlatLaf.style", estiloCampos);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkVigencia;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
