/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JIMMYSIN
 */
public class jdFuncionesMaterial extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdFuncionesMaterial.class.getName());

    // Definimos los modos posibles
    public enum Modo {
        AGREGAR, EDITAR, ELIMINAR
    }
    private Modo modoActual;
    private int idMaterialSeleccionado; // Para saber qué registro editar/eliminar

    /**
     * Creates new form jdFuncionesMaterial
     */
    public jdFuncionesMaterial(java.awt.Frame parent, boolean modal, Modo modo, int idMaterial) {
        super(parent, modal);
        initComponents();

        // Redondear los bordes del panel contenedor principal con FlatLaf
        // <-- Agregamos la llamada aquí
        aplicarEstiloBordesTecnicos();

        this.modoActual = modo;
        this.idMaterialSeleccionado = idMaterial;

        // Centramos la ventana en la pantalla
        this.setLocationRelativeTo(null);

        configurarModoVisual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelContenedor = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        spnStock = new javax.swing.JSpinner();
        txtDescripcion = new javax.swing.JTextField();
        chkVigencia = new javax.swing.JCheckBox();
        cboCategoria = new javax.swing.JComboBox<>();
        cboMarca = new javax.swing.JComboBox<>();
        btnNewCat = new javax.swing.JButton();
        btnNewMarca = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));

        lblNombre.setText("Nombre");

        lblCodigo.setText("Código");

        lblDescripcion.setText("Descripción");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        lblVigencia.setText("Vigencia");

        lblMarca.setText("Marca");

        lblCategoria.setText("Categoría");

        txtCodigo.addActionListener(this::txtCodigotxtCodigoActionPerformed);

        chkVigencia.setText("(Vigente)");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNewCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nuevo.png"))); // NOI18N

        btnNewMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nuevo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDescripcion)
                        .addComponent(lblCodigo)
                        .addComponent(lblNombre)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(txtNombre)
                        .addComponent(txtCodigo))
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                            .addComponent(lblStock)
                            .addGap(122, 122, 122))
                        .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelContenedorLayout.createSequentialGroup()
                            .addComponent(lblVigencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chkVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCategoria))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNewCat, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(btnNewMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblMarca))
                        .addGap(15, 15, 15))))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNombre)
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkVigencia)
                            .addComponent(lblVigencia))))
                .addGap(23, 23, 23)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addComponent(lblCategoria)
                                .addGap(17, 17, 17)
                                .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                                .addComponent(btnNewCat)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecio)
                                    .addComponent(lblMarca))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnNewMarca, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 330));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(232, 108, 54));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnGuardar.setText("| Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHideActionText(true);
        btnGuardar.setIconTextGap(15);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanelFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 180, -1));

        jLabel1.setFont(new java.awt.Font("Varsity Regular", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 101, 13));
        jLabel1.setText("gestión de materiales");
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 400, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoTecnico.png"))); // NOI18N
        jPanelFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 510, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigotxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigotxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigotxtCodigoActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setBackground(new Color(255, 200, 150));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Dependiendo del modo actual, ejecutamos la acción correspondiente
        switch (modoActual) {
            case AGREGAR:
                // TODO: Aquí llamas a tu método de la capa lógica para insertar
                // Ejemplo: objetoLogica.insertar(txtNombre.getText(), ...);
                JOptionPane.showMessageDialog(this, "Material registrado exitosamente.");
                break;

            case EDITAR:
                // TODO: Aquí llamas a tu método para actualizar usando el idMaterialSeleccionado
                // Ejemplo: objetoLogica.actualizar(idMaterialSeleccionado, txtNombre.getText(), ...);
                JOptionPane.showMessageDialog(this, "Material actualizado exitosamente.");
                break;

            case ELIMINAR:
                // TODO: Aquí llamas a tu método para eliminar o dar de baja
                // Ejemplo: objetoLogica.eliminar(idMaterialSeleccionado);
                JOptionPane.showMessageDialog(this, "Material eliminado exitosamente.");
                break;
        }

        // Cierra la ventana emergente después de realizar la acción
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarModoVisual() {
        switch (modoActual) {
            case AGREGAR:
                setTitle("Registrar Nuevo Material");
                // Asegúrate de que el nombre de tu botón en el diseño sea 'btnGuardar' 
                // o cámbialo por el nombre real de tu botón de acción principal.
                btnGuardar.setText("GUARDAR");
                limpiarCampos();
                break;

            case EDITAR:
                setTitle("Editar Material");
                btnGuardar.setText("ACTUALIZAR");
                cargarDatosMaterial(idMaterialSeleccionado);
                break;

            case ELIMINAR:
                setTitle("Eliminar Material");
                btnGuardar.setText("ELIMINAR");
                cargarDatosMaterial(idMaterialSeleccionado);
                bloquearCampos(false);
                break;
        }
    }

    private void bloquearCampos(boolean activar) {
        txtCodigo.setEnabled(activar);
        txtNombre.setEnabled(activar);
        txtDescripcion.setEnabled(activar);

        txtPrecio.setEnabled(activar);
        // Agrega aquí los demás txt o combo box si los tienes
    }

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");

        txtPrecio.setText("");
    }

    private void cargarDatosMaterial(int id) {
        // Aquí luego pondrás el código que llama a tu capa lógica/base de datos 
        // para buscar el material por su ID y rellenar los JTextField.
    }

    private void aplicarEstiloBordesTecnicos() {
        // Estilo limpio para JTextFields y Spinner (usando focusWidth en lugar de borderWidth)
        String estiloCampos = "arc: 4; borderWidth: 1; borderColor: #000099; focusColor: #EB5A0A;";

        txtCodigo.putClientProperty("FlatLaf.style", estiloCampos);
        txtNombre.putClientProperty("FlatLaf.style", estiloCampos);
        txtDescripcion.putClientProperty("FlatLaf.style", estiloCampos);
        txtPrecio.putClientProperty("FlatLaf.style", estiloCampos);
        spnStock.putClientProperty("FlatLaf.style", estiloCampos);

        // Estilo seguro para ComboBoxes
        String estiloCombo = "arc: 4; borderColor: #000099;";
        cboCategoria.putClientProperty("FlatLaf.style", estiloCombo);
        cboMarca.putClientProperty("FlatLaf.style", estiloCombo);

        // Estilo seguro para botones "NEW" (sin 'arc' directo para evitar excepciones)
        String estiloBotonNew = "borderWidth: 1; borderColor: #000099; focusColor: #EB5A0A;";
        btnNewCat.putClientProperty("FlatLaf.style", estiloBotonNew);
        btnNewMarca.putClientProperty("FlatLaf.style", estiloBotonNew);

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNewCat;
    private javax.swing.JButton btnNewMarca;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JCheckBox chkVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
