/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Componentes.UtilidadFuentes;
import capa_datos.ProyectoDAO;
import capa_logica.Proyecto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class jdManProyecto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdManProyecto.class.getName());


    public enum Modo {
        AGREGAR,
        EDITAR,
        ELIMINAR
    }

    private Modo modoActual;
    private String idProyectoSeleccionado;


    public jdManProyecto(java.awt.Frame parent, boolean modal, Modo modo, String codigoProyecto) {
        super(parent, modal);
        initComponents();
        
        setResizable(false);
        
        lblTitle.setFont(UtilidadFuentes.cargarFuenteVarsity(28f));
        aplicarEstiloBordesTecnicos();

        this.modoActual = modo;
        this.idProyectoSeleccionado = codigoProyecto;

        setLocationRelativeTo(null);

        configurarModoVisual();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelContenedor = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));

        lblNombre.setText("Nombre");

        lblCodigo.setText("Código");

        txtCodigo.addActionListener(this::txtCodigotxtCodigoActionPerformed);

        lblCodigo1.setText("Ubicacion");

        txtUbicacion.addActionListener(this::txtUbicaciontxtCodigoActionPerformed);

        lblNombre1.setText("Responsable");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo1)
                    .addComponent(lblNombre1)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtUbicacion)
                    .addComponent(txtResponsable))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(10, 10, 10)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCodigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre1)
                .addGap(10, 10, 10)
                .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanelFondo.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 400, 300));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(232, 108, 54));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnGuardar.setText("| Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHideActionText(true);
        btnGuardar.setIconTextGap(15);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanelFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 180, -1));

        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setText("Gestión de Proyectos");
        jPanelFondo.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 400, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoTecnico.png"))); // NOI18N
        jPanelFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 510, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(true);
        btnGuardar.setBackground(new Color(255, 200, 150));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnGuardarMouseExited
    private void aplicarEstiloBordesTecnicos() {
        // Estilo limpio para JTextFields y Spinner (usando focusWidth en lugar de borderWidth)
        String estiloCampos = "arc: 4; borderWidth: 1; borderColor: #000099; focusColor: #EB5A0A;";

        txtCodigo.putClientProperty("FlatLaf.style", estiloCampos);
        txtNombre.putClientProperty("FlatLaf.style", estiloCampos);
        txtUbicacion.putClientProperty("FlatLaf.style", estiloCampos);
        txtResponsable.putClientProperty("FlatLaf.style", estiloCampos);

    }
    
    private void bloquearCampos(boolean activar) {

        txtCodigo.setEnabled(activar);
        txtNombre.setEnabled(activar);
        txtUbicacion.setEnabled(activar);
        txtResponsable.setEnabled(activar);

    }
    
    private void configurarModoVisual() {

        switch(modoActual) {

            case AGREGAR:

                setTitle("Registrar Proyecto");
                btnGuardar.setText("GUARDAR");
                limpiarCampos();
                txtCodigo.setEditable(true);

                break;

            case EDITAR:

                setTitle("Editar Proyecto");
                btnGuardar.setText("ACTUALIZAR");

                cargarProyecto();
                txtCodigo.setEditable(false);


                break;

            case ELIMINAR:

                setTitle("Eliminar Proyecto");
                btnGuardar.setText("ELIMINAR");

                cargarProyecto();
                bloquearCampos(false);

                break;
        }

    }
    
    private void cargarProyecto() {

        try {

            Proyecto p = ProyectoDAO.consultarPorCodigo(idProyectoSeleccionado);

            if (p != null) {
                txtCodigo.setText(p.getCodigo());
                txtNombre.setText(p.getNombre());
                txtUbicacion.setText(p.getUbicacion());
                txtResponsable.setText(p.getResponsable());
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }
    }    
    
    
    
    private boolean validarCampos(){

        if(txtCodigo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Ingrese el código.");
            txtCodigo.requestFocus();
            return false;
        }

        if(txtNombre.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Ingrese el nombre.");
            txtNombre.requestFocus();
            return false;
        }

        if(txtUbicacion.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Ingrese la ubicación.");
            txtUbicacion.requestFocus();
            return false;
        }

        if(txtResponsable.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Ingrese el responsable.");
            txtResponsable.requestFocus();
            return false;
        }

        return true;
    }
    
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Dependiendo del modo actual, ejecutamos la acción correspondiente
        try {

            switch (modoActual) {

                case AGREGAR:

                    if (!validarCampos())
                        return;

                    if (ProyectoDAO.consultarPorCodigo(txtCodigo.getText().trim()) != null) {

                        JOptionPane.showMessageDialog(this,
                                "Ya existe un proyecto con ese código.");

                        return;
                    }

                    Proyecto nuevo = new Proyecto(
                            txtCodigo.getText().trim(),
                            txtNombre.getText().trim(),
                            txtUbicacion.getText().trim(),
                            txtResponsable.getText().trim());

                    ProyectoDAO.agregar(nuevo);

                    JOptionPane.showMessageDialog(this,
                            "Proyecto registrado correctamente.");

                    break;

                case EDITAR:

                    if (!validarCampos())
                        return;

                    Proyecto actualizado = new Proyecto(
                            idProyectoSeleccionado,
                            txtNombre.getText().trim(),
                            txtUbicacion.getText().trim(),
                            txtResponsable.getText().trim());

                    ProyectoDAO.modificar(actualizado);

                    JOptionPane.showMessageDialog(this,
                            "Proyecto actualizado correctamente.");

                    break;

                case ELIMINAR:

                    int r = JOptionPane.showConfirmDialog(this,
                            "¿Eliminar el proyecto?",
                            "Confirmación",
                            JOptionPane.YES_NO_OPTION);

                    if (r != JOptionPane.YES_OPTION)
                        return;

                    ProyectoDAO.borrar(idProyectoSeleccionado);

                    JOptionPane.showMessageDialog(this,
                            "Proyecto eliminado.");

                    break;
            }

            dispose();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage());

        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCodigotxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigotxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigotxtCodigoActionPerformed

    private void txtUbicaciontxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicaciontxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicaciontxtCodigoActionPerformed

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtUbicacion.setText("");
        txtResponsable.setText("");       
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
